start_epoch: 0
epochs: 600
resume_frm_chck_pt: False
force_save_model: False
reset_optimizer_state: False
restrict_seqlen: -1
train_model: True
student_list:
  [

    "student 1",
    "student 2",
    "student 12",
    "student 15",
    "student 24",
    "student 27",
    "student 30",
    "student 35",
    "student 42",
    "student 52",

                  ]

feature_list: [

        "activity_details",
        "audio_details",
        "sms_details",
        "call_log_details",
        "conversation_details",
        "dark_details",
        "gps_details",
        "phonecharge_details",
        "phonelock_details",
        "sleep_details"

      ]

train_split: -1