start_epoch: 0
epochs: 1000
resume_frm_chck_pt: False
force_save_model: False
reset_optimizer_state: False
restrict_seqlen: 10
train_model: True
student_list:
  [
      "student 1"
                  ]

feature_list: [

        "activity_details",
        "audio_details",
        "sms_details",
        "call_log_details",
        "conversation_details",
        "dark_details",
        "gps_details",
        "phonecharge_details",
        "phonelock_details",
        "sleep_details"

      ]

train_split: -1