start_epoch: 0
epochs: 200
resume_frm_chck_pt: False
force_save_model: True
reset_optimizer_state: True
restrict_seqlen: -1
train_model: True
student_list:
  [
      "student 1",
      "student 5",
      "student 8",
      "student 15",
      "student 18",
      "student 20",
      "student 23",
      "student 25",
      "student 32",
      "student 39",
      "student 45",
      "student 46",
      "student 52",
      "student 56"
                  ]

feature_list: [

        "activity_details",
        "audio_details",
        "sms_details",
        "call_log_details",
        "conversation_details",
        "dark_details",
        "gps_details",
        "phonecharge_details",
        "phonelock_details",
        "sleep_details"

      ]

train_split: -1